"""Module description docstring."""

# You can use this pattern to hide data from Sphinx
try:
    if __sphinx_build__:
        # Code executed when documentation is being built
        SECRET_VALUE = "dummy value."
        """The real value is hidden from Sphinx..."""
        
except NameError:
    # This will run if the file is called anywhere but from sphinx doc
    SECRET_VALUE = "12345678"
    """This is the real value, but Sphinx cannot read it..."""

# The option undoc-members does not work for modules, which means the following
# constant will not appear in the autogenerated doc. This is a Sphinx issue, and
# a good motivation to document your module constants.
NOT_DOCUMENTED = 3
